---
kind: pipeline
name: speedtest
type: docker

steps:
- name: Build
  image: plugins/docker
  settings:
    repo: registry.lukemilius.com/speedtest
    registry: registry.lukemilius.com
    auto_tag: true
